# Generated by Django 4.2.20 on 2025-04-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='guets_pause',
            new_name='guests_pause',
        ),
    ]
